Recommend libusb0 instead of libusb1 on Windows
Using libusb1 on Windows yields the following error:

	usb.core.USBError: [Errno 5] Input/Output Error